(deftheme badger
  "Created 2022-01-31.")

(custom-theme-set-variables
 'badger
 '(ansi-color-names-vector ["black" "#E2434C" "#86B187" "#E0D063" "#84C452" "#E18CBB" "#8AC6F2" "white"]))

(custom-theme-set-faces
 'badger
 '(button ((t (:underline t))))
 '(link ((t (:bold t :foreground "#8AC6F2" :underline t :weight bold))))
 '(cursor ((t (:background "#F28B86"))))
 '(escape-glyph ((t (:foreground "#F28B86" :bold t))))
 '(fringe ((t (:foreground "#F6F3E8" :background "black"))))
 '(highlight ((t (:background "#1D1D1D"))))
 '(lazy-highlight ((t (:background "#E0D063" :foreground "black" :weight extra-bold))))
 '(isearch ((t (:background "cyan" :foreground "black" :weight extra-bold))))
 '(success ((t (:foreground "#8ACDAA" :weight bold))))
 '(warning ((t (:foreground "#E18CBB" :weight bold))))
 '(region ((t (:background "black"))))
 '(show-paren-match-face ((t (:background "#84C452" :foreground "black"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#656868" :background "black")) (t :inverse-video nil)))
 '(mode-line-inactive ((t (:background "#2F2F2F" :foreground "black" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#F28B86"))))
 '(minibuffer-prompt ((t (:foreground "#BF93C3"))))
 '(linum ((t (:foreground "#656868" :background "black"))))
 '(font-lock-warning-face ((t (:foreground "#E0D063" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#EA9847"))))
 '(font-lock-variable-name-face ((t (:foreground "#F28B86"))))
 '(font-lock-keyword-face ((t (:foreground "#8AC6F2"))))
 '(font-lock-comment-face ((t (:foreground "#656868"))))
 '(font-lock-type-face ((t (:foreground "##FFC469"))))
 '(font-lock-constant-face ((t (:foreground "#635770"))))
 '(font-lock-builtin-face ((t (:foreground "#BF93C3"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FFC469"))))
 '(font-lock-string-face ((t (:foreground "#86B187"))))
 '(eshell-prompt ((t (:foreground "#84C452"))))
 '(eshell-ls-archive ((t (:foreground "#EA9847" :weight bold))))
 '(eshell-ls-backup ((t (:inherit font-lock-comment-face))))
 '(eshell-ls-clutter ((t (:inherit font-lock-comment-face))))
 '(eshell-ls-directory ((t (:foreground "#BF93C3" :weight normal))))
 '(eshell-ls-executable ((t (:foreground "#E0D063" :weight normal))))
 '(eshell-ls-unreadable ((t (:foreground "#F6F3E8"))))
 '(eshell-ls-missing ((t (:inherit font-lock-warning-face))))
 '(eshell-ls-product ((t (:inherit font-lock-doc-face))))
 '(eshell-ls-special ((t (:foreground "#8AC6F2" :weight bold))))
 '(eshell-ls-symlink ((t (:foreground "#8ACDAA" :weight bold))))
 '(org-document-info-keyword ((t (:foreground "#9AA68E"))))
 '(org-document-title ((t (:foreground "#F28B86" :height 1.5))))
 '(org-archived ((t (:foreground "#F6F3E8" :weight bold))))
 '(org-checkbox ((t (:foreground "#FBF9F3" :foreground "#9AA68E" :box (:line-width 1 :style released-button)))))
 '(org-done ((t (:foreground "#84C452" :strike-through t))))
 '(org-todo ((t (:foreground "#E2434C"))))
 '(org-formula ((t (:foreground "#BF93C3"))))
 '(org-headline-done ((t (:strike-through t :foreground "#656868"))))
 '(org-hide ((t (:foreground "#171717"))))
 '(org-level-1 ((t (:foreground "#8AC6F2"))))
 '(org-level-2 ((t (:foreground "#BF93C3"))))
 '(org-level-3 ((t (:foreground "#EA9847"))))
 '(org-level-4 ((t (:foreground "#E0D063"))))
 '(org-level-5 ((t (:foreground "#F28B86"))))
 '(org-level-6 ((t (:foreground "#86B187"))))
 '(org-level-7 ((t (:foreground "#AC8952"))))
 '(org-level-8 ((t (:foreground "#65A399"))))
 '(org-link ((t (:foreground "#8ACDAA" :underline t))))
 '(org-agenda-date ((t (:foreground "#8AC6F2"))))
 '(org-deadline-announce ((t (:foreground "#A55662"))))
 '(org-date ((t (:foreground "#8ACDAA" :underline t))))
 '(org-agenda-date-today ((t (:foreground "#F28B86" :weight light :slant italic))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-special-keyword ((t (:foreground "#9AA68E" :weight normal))))
 '(org-table ((t (:foreground "#9AA68E"))))
 '(org-tag ((t (:bold t :foreground "#EA9847" :strike-through nil))))
 '(org-warning ((t (:bold t :foreground "#E18CBB" :weight bold))))
 '(org-column ((t (:background "black"))))
 '(org-column-title ((t (:background "black" :foreground "#84C452" :underline t))))
 '(org-mode-line-clock ((t (:foreground "#E0D063"))))
 '(org-footnote ((t (:foreground "#8ACDAA" :underline t))))
 '(org-code ((t (:foreground "#9AA68E"))))
 '(org-verbatim ((t (:inherit org-code))))
 '(highlight-indentation-face ((t (:background "#171717"))))
 '(comint-highlight-prompt ((t (:inherit eshell-prompt))))
 '(ac-candidate-face ((t (:background "#C7B299" :foreground "black"))))
 '(ac-selection-face ((t (:background "#BF93C3" :foreground "black"))))
 '(popup-tip-face ((t (:background "#C7B299" :foreground "black"))))
 '(popup-scroll-bar-foreground-face ((t (:background "#635770"))))
 '(popup-scroll-bar-background-face ((t (:background "#9AA68E"))))
 '(popup-isearch-match ((t (:background "#E0D063" :foreground "black"))))
 '(sml/folder ((t (:foreground "#656868"))))
 '(sml/filename ((t (:foreground "#F28B86" :weight normal))))
 '(sml/prefix ((t (:foreground "#F28B86" :weight normal))))
 '(sml/line-number ((t (:foreground "#8AC6F2" :weight normal))))
 '(sml/col-number ((t (:foreground "#86B187" :weight normal))))
 '(sml/read-only ((t (:foreground "#656868"))))
 '(sml/outside-modified ((t (:foreground "#E2434C"))))
 '(sml/modified ((t (:foreground "#E2434C"))))
 '(sml/remote ((t (:foreground "#656868"))))
 '(sml/numbers-separator ((t (:foreground "#656868"))))
 '(sml/git ((t (:foreground "#8AC6F2"))))
 '(sml/vc-edited ((t (:foreground "#8AC6F2"))))
 '(sml/modes ((t (:foreground "#E18CBB"))))
 '(sml/position-percentage ((t (:foreground "#656868"))))
 '(flyspell-incorrect ((t (:underline (:color "#E2434C" :style wave)))))
 '(flyspell-duplicate ((t (:underline (:color "#E0D063" :style wave)))))
 '(default ((t (:foreground "#F6F3E8" :background "#171717")))))

(provide-theme 'badger)
